name: unified-ms-env
channels:
  - conda-forge
  - bioconda
  - pyg
dependencies:
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiohttp-cors=0.8.1
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - annotated-types=0.7.0
  - async-timeout=5.0.1
  - atk-1.0=2.38.0
  - attr=2.5.2
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.21.0
  - aws-c-mqtt=0.13.1
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - backcall=0.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.3
  - click=8.1.8
  - colorama=0.4.6
  - colorful=0.5.6
  - contourpy=1.3.0
  - cryptography=45.0.6
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cython=3.1.3
  - dbus=1.13.6
  - debugpy=1.8.16
  - decorator=5.2.1
  - deprecated=1.2.18
  - distlib=0.4.0
  - einops=0.8.1
  - expat=2.7.1
  - filelock=3.19.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.1
  - freetype=2.14.1
  - freetype-py=2.3.0
  - fribidi=1.0.16
  - frozenlist=1.7.0
  - fsspec=2025.7.0
  - gdk-pixbuf=2.42.12
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - glib=2.84.0
  - glib-tools=2.84.0
  - glog=0.7.1
  - google-api-core=2.25.1
  - google-auth=2.40.3
  - googleapis-common-protos=1.70.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - greenlet=3.2.4
  - grpcio=1.71.0
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - gtk2=2.24.33
  - gts=0.7.6
  - h2=4.2.0
  - h5py=3.14.0
  - harfbuzz=11.0.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipdb=0.13.13
  - ipykernel=6.0.3
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - jedi=0.19.2
  - joblib=1.5.1
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.4.1
  - jupyter_client=6.1.12
  - jupyter_core=5.8.1
  - keyutils=1.6.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.4
  - libarrow=20.0.0
  - libarrow-acero=20.0.0
  - libarrow-dataset=20.0.0
  - libarrow-substrait=20.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.76
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=21.1.0
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.5.2
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgcrypt-lib=1.11.1
  - libgd=2.3.3
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgpg-error=1.55
  - libgrpc=1.71.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libopus=1.5.2
  - libparquet=20.0.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.29.3
  - librdkit=2024.09.4
  - libre2-11=2025.06.26
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=257.9
  - libthrift=0.21.0
  - libtiff=4.7.1
  - libunwind=1.8.3
  - libutf8proc=2.10.0
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=21.1.3
  - lz4-c=1.10.0
  - matchms
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.7
  - mkl=2024.0.0
  - mpg123=1.32.9
  - msgpack-python=1.1.1
  - multidict=6.6.3
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nb_conda_kernels=2.3.1
  - ncurses=6.5
  - nlohmann_json=3.12.0
  - nspr=4.37
  - nss=3.117
  - numpy=1.23.5
  - opencensus=0.11.3
  - opencensus-context=0.1.3
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.5.4
  - opentelemetry-api=1.35.0
  - opentelemetry-exporter-prometheus=0.56b0
  - opentelemetry-proto=1.36.0
  - opentelemetry-sdk=1.35.0
  - opentelemetry-semantic-conventions=0.56b0
  - orc=2.1.2
  - packaging=25.0
  - pandas=1.4.4
  - pango=1.56.3
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.8
  - ply=3.11
  - prometheus-cpp=1.3.0
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - proto-plus=1.26.1
  - protobuf=5.29.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - py-spy=0.4.1
  - pyarrow=20.0.0
  - pyarrow-core=20.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycairo=1.28.0
  - pycparser=2.22
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pygraphviz=1.7
  - pyopenssl=25.1.0
  - pyparsing=3.2.3
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pysocks=1.7.1
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python-graphviz=0.17
  - python_abi=3.9
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - pyzmq=27.0.2
  - qt-main=5.15.15
  - ray-core=2.48.0
  - ray-default=2.48.0
  - ray-tune=2.48.0
  - rdkit=2024.09.4
  - re2=2025.06.26
  - readline=8.2
  - referencing=0.36.2
  - reportlab=4.4.1
  - requests=2.32.5
  - rlpycairo=0.2.0
  - rpds-py=0.27.0
  - rsa=4.9.1
  - s2n=1.5.22
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setproctitle=1.3.6
  - setuptools=68.0.0
  - sip=6.10.0
  - six=1.17.0
  - smart_open=7.3.0.post1
  - snappy=1.2.2
  - sqlalchemy=2.0.43
  - statsmodels=0.14.5
  - tbb=2021.13.0
  - tensorboardx=2.6.2.2
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.14.1
  - typing-inspection=0.4.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - virtualenv=20.34.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.3
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxrender=0.9.12
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
    - -r requirements.txt